[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "wg-async-foundations"

[rust]
edition = "2018"

[output.html]
site-url = "/wg-async-foundations/"
git-repository-url = "https://github.com/rust-lang/wg-async-foundations"
additional-js =["mermaid.min.js", "mermaid-init.js", "viz.js", "full.render.js", "panzoom.min.js", "skill-tree.js"]
additional-css =["skill-tree.css"]

[output.html.fold]
enable = true
level = 0
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
[preprocessor.skill-tree]
command = "mdbook-skill-tree"
